---
abstract: 'We are British CPAN authors'
author:
  - 'Barbie <barbie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-British
no_index:
  directory:
    - t
    - inc
requires:
  Acme::CPANAuthors: 0.04
  IO::File: 0
  Test::More: 0.70
version: 0.07
